# ═══════════════════════════════════════════════════════════════════
# Google Cloud Build configuration for Cloud Run deployment
# ═══════════════════════════════════════════════════════════════════

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aml-node-backend:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/aml-node-backend:latest'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aml-node-backend:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/aml-node-backend:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aml-node-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/aml-node-backend:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUD_SQL_INSTANCE}'
      - '--set-env-vars'
      - 'NODE_ENV=production,DB_SOCKET_PATH=/cloudsql,DB_INSTANCE_CONNECTION_NAME=${_CLOUD_SQL_INSTANCE}'
      - '--min-instances'
      - '${_MIN_INSTANCES}'
      - '--max-instances'
      - '${_MAX_INSTANCES}'
      - '--memory'
      - '${_MEMORY}'
      - '--cpu'
      - '${_CPU}'
      - '--concurrency'
      - '${_CONCURRENCY}'
      - '--timeout'
      - '60s'

# Substitution variables (set these in Cloud Build trigger or command line)
substitutions:
  _REGION: us-central1
  _CLOUD_SQL_INSTANCE: 'project-id:region:instance-name'
  _MIN_INSTANCES: '0'
  _MAX_INSTANCES: '10'
  _MEMORY: '512Mi'
  _CPU: '1'
  _CONCURRENCY: '80'

# Store images in Container Registry
images:
  - 'gcr.io/$PROJECT_ID/aml-node-backend:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/aml-node-backend:latest'

# Build timeout
timeout: '600s'

options:
  logging: CLOUD_LOGGING_ONLY
